/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ERC2771ContextUpgradeable,
  ERC2771ContextUpgradeableInterface,
} from "../../../../src/contracts/metatx/ERC2771ContextUpgradeable";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "oldTF",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newTF",
        type: "address",
      },
    ],
    name: "TrustedForwarderChanged",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "forwarder",
        type: "address",
      },
    ],
    name: "isTrustedForwarder",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060de8061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063572b6c0514602d575b600080fd5b60596038366004606d565b60335473ffffffffffffffffffffffffffffffffffffffff91821691161490565b604051901515815260200160405180910390f35b600060208284031215607e57600080fd5b813573ffffffffffffffffffffffffffffffffffffffff8116811460a157600080fd5b939250505056fea2646970667358221220dedf0e300ecce38081a6b6dd77fd7258dbc5250a0e0c6100f9528e1086280f6264736f6c63430008070033";

type ERC2771ContextUpgradeableConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ERC2771ContextUpgradeableConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ERC2771ContextUpgradeable__factory extends ContractFactory {
  constructor(...args: ERC2771ContextUpgradeableConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ERC2771ContextUpgradeable> {
    return super.deploy(overrides || {}) as Promise<ERC2771ContextUpgradeable>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): ERC2771ContextUpgradeable {
    return super.attach(address) as ERC2771ContextUpgradeable;
  }
  override connect(signer: Signer): ERC2771ContextUpgradeable__factory {
    return super.connect(signer) as ERC2771ContextUpgradeable__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ERC2771ContextUpgradeableInterface {
    return new utils.Interface(_abi) as ERC2771ContextUpgradeableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC2771ContextUpgradeable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ERC2771ContextUpgradeable;
  }
}
