/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ERC2771ContextUpgradeable,
  ERC2771ContextUpgradeableInterface,
} from "../../../../src/contracts/metatx/ERC2771ContextUpgradeable";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "oldTF",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newTF",
        type: "address",
      },
    ],
    name: "TrustedForwarderChanged",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "forwarder",
        type: "address",
      },
    ],
    name: "isTrustedForwarder",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061023d806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063572b6c0514610030575b600080fd5b61004a60048036038101906100459190610156565b610060565b6040516100579190610192565b60405180910390f35b600061008e7fa6c9292c92ca93343067f17c3ec7cc3474a3f2da822b028d7a2251425d4bc11760001b61013e565b6100ba7f6b919852df0b626a8a37a21e9fc984db97a099e9e7aff99563e021ae74ef670d60001b61013e565b6100e67fdc2ecbdae383f4c1d35650a87d70eed09955a62c0e173893d79859b820b007c860001b61013e565b603360009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168273ffffffffffffffffffffffffffffffffffffffff16149050919050565b50565b600081359050610150816101f0565b92915050565b60006020828403121561016c5761016b6101eb565b5b600061017a84828501610141565b91505092915050565b61018c816101bf565b82525050565b60006020820190506101a76000830184610183565b92915050565b60006101b8826101cb565b9050919050565b60008115159050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600080fd5b6101f9816101ad565b811461020457600080fd5b5056fea2646970667358221220fe77a3f95afe9cc097a814a7b2c49921c848a67e02f83c81cef45a1e159d418d64736f6c63430008070033";

type ERC2771ContextUpgradeableConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ERC2771ContextUpgradeableConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ERC2771ContextUpgradeable__factory extends ContractFactory {
  constructor(...args: ERC2771ContextUpgradeableConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ERC2771ContextUpgradeable> {
    return super.deploy(overrides || {}) as Promise<ERC2771ContextUpgradeable>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): ERC2771ContextUpgradeable {
    return super.attach(address) as ERC2771ContextUpgradeable;
  }
  override connect(signer: Signer): ERC2771ContextUpgradeable__factory {
    return super.connect(signer) as ERC2771ContextUpgradeable__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ERC2771ContextUpgradeableInterface {
    return new utils.Interface(_abi) as ERC2771ContextUpgradeableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC2771ContextUpgradeable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ERC2771ContextUpgradeable;
  }
}
