/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  ERC2771ContextUpgradeable,
  ERC2771ContextUpgradeableInterface,
} from "../../../contracts/metatx/ERC2771ContextUpgradeable";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "oldTF",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newTF",
        type: "address",
      },
    ],
    name: "TrustedForwarderChanged",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "forwarder",
        type: "address",
      },
    ],
    name: "isTrustedForwarder",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061023d806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063572b6c0514610030575b600080fd5b61004a60048036038101906100459190610156565b610060565b6040516100579190610192565b60405180910390f35b600061008e7f4fdbcc86804f903cdf56f31a6adac3f00e8e7aba6650929eaa81a85e1e9eb49760001b61013e565b6100ba7f6db1d7bf479fbd8a74cb4ad2fc38059659f199a3d06427d2574cae9f1855c2f060001b61013e565b6100e67f1de9ac4b3e29409c3711f2b637b481c6fa1963b60d035f3d5e80b7e92162dda260001b61013e565b603360009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168273ffffffffffffffffffffffffffffffffffffffff16149050919050565b50565b600081359050610150816101f0565b92915050565b60006020828403121561016c5761016b6101eb565b5b600061017a84828501610141565b91505092915050565b61018c816101bf565b82525050565b60006020820190506101a76000830184610183565b92915050565b60006101b8826101cb565b9050919050565b60008115159050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600080fd5b6101f9816101ad565b811461020457600080fd5b5056fea264697066735822122089caba32119dc482f2b3ecc13b78a24ba0fe5e162c939f2855e5f3078647291b64736f6c63430008070033";

type ERC2771ContextUpgradeableConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ERC2771ContextUpgradeableConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ERC2771ContextUpgradeable__factory extends ContractFactory {
  constructor(...args: ERC2771ContextUpgradeableConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ERC2771ContextUpgradeable> {
    return super.deploy(overrides || {}) as Promise<ERC2771ContextUpgradeable>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): ERC2771ContextUpgradeable {
    return super.attach(address) as ERC2771ContextUpgradeable;
  }
  override connect(signer: Signer): ERC2771ContextUpgradeable__factory {
    return super.connect(signer) as ERC2771ContextUpgradeable__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ERC2771ContextUpgradeableInterface {
    return new utils.Interface(_abi) as ERC2771ContextUpgradeableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC2771ContextUpgradeable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ERC2771ContextUpgradeable;
  }
}
