/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export declare namespace ERC2771ForwarderMock {
  export type ForwardRequestStruct = {
    from: string;
    to: string;
    value: BigNumberish;
    gas: BigNumberish;
    nonce: BigNumberish;
    data: BytesLike;
  };

  export type ForwardRequestStructOutput = [
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    string
  ] & {
    from: string;
    to: string;
    value: BigNumber;
    gas: BigNumber;
    nonce: BigNumber;
    data: string;
  };
}

export interface ERC2771ForwarderMockInterface extends utils.Interface {
  functions: {
    "execute((address,address,uint256,uint256,uint256,bytes))": FunctionFragment;
    "getNonce(address)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "execute" | "getNonce"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "execute",
    values: [ERC2771ForwarderMock.ForwardRequestStruct]
  ): string;
  encodeFunctionData(functionFragment: "getNonce", values: [string]): string;

  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getNonce", data: BytesLike): Result;

  events: {
    "Forwarded(bool,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Forwarded"): EventFragment;
}

export interface ForwardedEventObject {
  arg0: boolean;
  arg1: string;
}
export type ForwardedEvent = TypedEvent<
  [boolean, string],
  ForwardedEventObject
>;

export type ForwardedEventFilter = TypedEventFilter<ForwardedEvent>;

export interface ERC2771ForwarderMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ERC2771ForwarderMockInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    execute(
      req: ERC2771ForwarderMock.ForwardRequestStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getNonce(from: string, overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  execute(
    req: ERC2771ForwarderMock.ForwardRequestStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getNonce(from: string, overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    execute(
      req: ERC2771ForwarderMock.ForwardRequestStruct,
      overrides?: CallOverrides
    ): Promise<[boolean, string]>;

    getNonce(from: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "Forwarded(bool,bytes)"(arg0?: null, arg1?: null): ForwardedEventFilter;
    Forwarded(arg0?: null, arg1?: null): ForwardedEventFilter;
  };

  estimateGas: {
    execute(
      req: ERC2771ForwarderMock.ForwardRequestStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getNonce(from: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    execute(
      req: ERC2771ForwarderMock.ForwardRequestStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getNonce(
      from: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
