/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1363ReceiverMock } from "./ERC1363ReceiverMock";
export type { ERC1363SpenderMock } from "./ERC1363SpenderMock";
export type { ERC2771ForwarderMock } from "./ERC2771ForwarderMock";
