/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Signer,
  utils,
  Contract,
  ContractFactory,
  BytesLike,
  Overrides,
} from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ERC1363SpenderMock,
  ERC1363SpenderMockInterface,
} from "../../../../src/contracts/mocks/ERC1363SpenderMock";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "retval",
        type: "bytes4",
      },
      {
        internalType: "bool",
        name: "reverts",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "gas",
        type: "uint256",
      },
    ],
    name: "Approved",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onApprovalReceived",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516103be3803806103be83398101604081905261002f91610059565b600080549115156401000000000264ffffffffff1990921660e09390931c929092171790556100a5565b6000806040838503121561006c57600080fd5b82516001600160e01b03198116811461008457600080fd5b6020840151909250801515811461009a57600080fd5b809150509250929050565b61030a806100b46000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80637b04a2d014610030575b600080fd5b61004361003e36600461013d565b610078565b6040517fffffffff00000000000000000000000000000000000000000000000000000000909116815260200160405180910390f35b60008054640100000000900460ff16156100f2576040517f08c379a000000000000000000000000000000000000000000000000000000000815260206004820152601c60248201527f455243313336335370656e6465724d6f636b3a207468726f77696e6700000000604482015260640160405180910390fd5b7fe7c2bad6c6b2105a7cfcf604a9b58fc7f698a6bd195c88ea6242427303eaa51b8484845a6040516101279493929190610223565b60405180910390a15060005460e01b9392505050565b60008060006060848603121561015257600080fd5b833573ffffffffffffffffffffffffffffffffffffffff8116811461017657600080fd5b925060208401359150604084013567ffffffffffffffff8082111561019a57600080fd5b818601915086601f8301126101ae57600080fd5b8135818111156101c0576101c06102a5565b604051601f8201601f19908116603f011681019083821181831017156101e8576101e86102a5565b8160405282815289602084870101111561020157600080fd5b8260208601602083013760006020848301015280955050505050509250925092565b73ffffffffffffffffffffffffffffffffffffffff8516815260006020858184015260806040840152845180608085015260005b818110156102735786810183015185820160a001528201610257565b8181111561028557600060a083870101525b5060608401949094525050601f91909101601f19160160a0019392505050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052604160045260246000fdfea264697066735822122004effd052a2475ee53c2d6c7fd2c43d5a65655d1e8687a6d9e5172e51397b2ac64736f6c63430008070033";

type ERC1363SpenderMockConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ERC1363SpenderMockConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ERC1363SpenderMock__factory extends ContractFactory {
  constructor(...args: ERC1363SpenderMockConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    retval: BytesLike,
    reverts: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ERC1363SpenderMock> {
    return super.deploy(
      retval,
      reverts,
      overrides || {}
    ) as Promise<ERC1363SpenderMock>;
  }
  override getDeployTransaction(
    retval: BytesLike,
    reverts: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(retval, reverts, overrides || {});
  }
  override attach(address: string): ERC1363SpenderMock {
    return super.attach(address) as ERC1363SpenderMock;
  }
  override connect(signer: Signer): ERC1363SpenderMock__factory {
    return super.connect(signer) as ERC1363SpenderMock__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ERC1363SpenderMockInterface {
    return new utils.Interface(_abi) as ERC1363SpenderMockInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC1363SpenderMock {
    return new Contract(address, _abi, signerOrProvider) as ERC1363SpenderMock;
  }
}
