/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export {ERC1363ReceiverMock__factory} from './ERC1363ReceiverMock__factory';
export {ERC1363SpenderMock__factory} from './ERC1363SpenderMock__factory';
export {ERC2771ForwarderMock__factory} from './ERC2771ForwarderMock__factory';
